In [58]:
# menu_embeddings = [get_embedding(item) for item in menu]
menu_embeddings = []
for item in menu:
  menu_embeddings.append(get_embedding(item))

KeyboardInterrupt: 

In [6]:
from openai import OpenAI
import numpy as np

# Initialize client
client = OpenAI(api_key=KEY)

# Menu
menu = ["Food", "Travel", "Clothes", "Games", "Read"]

# Function to get embeddings
def get_embedding(text, model="text-embedding-3-small"):
    response = client.embeddings.create(
        model=model,
        input=text
    )
    return np.array(response.data[0].embedding)

# Precompute menu embeddings
menu_embeddings = []
for item in menu:
    embedding = get_embedding(item)
    menu_embeddings.append(embedding)

import math
# Function to find closest menu index using Euclidean distance
def get_menu_index(user_input):
    user_embedding = get_embedding(user_input)
    
    distances = []
    for menu_embedding in menu_embeddings:
        # sqrt((x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2)....1536
        distance = math.sqrt(sum((user_embedding - menu_embedding)**2))
        distances.append(distance)
    
    min_index = 0
    min_distance = distances[0]
    for i in range(1, len(distances)):
        if distances[i] < min_distance:
            min_distance = distances[i]
            min_index = i
    
    return min_index

# Test
print(get_menu_index("Eat"))                     # Expected output: 0 (Food)
print(get_menu_index("I want to visit Toronto")) # Expected output: 1 (Travel)


0
1


In [7]:
while True:
    user_input = input("What do you want? ")
    idx = get_menu_index(user_input)
    print("You want: ", menu[idx])

What do you want? eat
You want:  Food


KeyboardInterrupt: Interrupted by user

In [ ]:

# Function to get embeddings
def get_embedding(text, model="text-embedding-3-small"):
    response = client.embeddings.create(
        model=model,
        input=text
    )
    return np.array(response.data[0].embedding)


In [8]:
result = get_embedding("Orthopedic")
print(result)

[-0.00461176  0.02267854  0.00471202 ...  0.0131093   0.02226369
 -0.00387195]


In [11]:
len(result)

1536

In [ ]:
import math

In [13]:
menu = [
    # Primary Care
    "General Practitioner (GP)",
    "Family Medicine Doctor",
    "Internal Medicine Doctor (Internist)",

    # Specialists
    "Cardiologist",
    "Dermatologist",
    "Endocrinologist",
    "Gastroenterologist",
    "Hematologist",
    "Nephrologist",
    "Neurologist",
    "Oncologist",
    "Pulmonologist",
    "Rheumatologist",

    # Surgeons
    "General Surgeon",
    "Orthopedic Surgeon",
    "Cardiothoracic Surgeon",
    "Neurosurgeon",
    "Plastic Surgeon",
    "Vascular Surgeon",

    # Pediatrics & Women’s Health
    "Pediatrician",
    "Pediatric Cardiologist",
    "Pediatric Neurologist",
    "Obstetrician (OB)",
    "Gynecologist (GYN)",
    "OB-GYN",

    # Mental Health & Behavioral
    "Psychiatrist",
    "Child Psychiatrist",
    "Psychologist",

    # Eye, Ear, Nose, Throat
    "Ophthalmologist",
    "Optometrist",
    "Otolaryngologist (ENT)",

    # Other Specialties
    "Allergist/Immunologist",
    "Anesthesiologist",
    "Radiologist",
    "Pathologist",
    "Urologist",
    "Infectious Disease Specialist"
]

# Precompute menu embeddings
menu_embeddings = []
for item in menu:
    embedding = get_embedding(item)
    menu_embeddings.append(embedding)


In [18]:
len(menu_embeddings[0])

1536

In [23]:
res1 = get_embedding("Cardiologist")
res2 = get_embedding("Cardiologist")

In [24]:
res1


array([-1.91078616e-05, -4.57503647e-02,  7.39358552e-03, ...,
        5.31711802e-03,  2.14046352e-02,  1.07772062e-02])

In [25]:
res2

array([-1.91078616e-05, -4.57503647e-02,  7.39358552e-03, ...,
        5.31711802e-03,  2.14046352e-02,  1.07772062e-02])

In [30]:
res3 = get_embedding("cardiologist")
res3

array([ 0.00193863, -0.04151899,  0.00893924, ...,  0.00167442,
        0.02408478,  0.00194704])

In [33]:
# Function to find closest menu index using Euclidean distance
def get_menu_index(user_input):
    user_embedding = get_embedding(user_input)
    
    distances = []
    for i, menu_embedding in enumerate(menu_embeddings):
        # sqrt((x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2)....1536
        distance = math.sqrt(sum((user_embedding - menu_embedding)**2))
        distances.append(distance)
#         print(f"Distance: {menu[i]} <> {distance} ")
    
    min_index = 0
    min_distance = distances[0]
    for i in range(1, len(distances)):
        if distances[i] < min_distance:
            min_distance = distances[i]
            min_index = i
    
    return min_index

In [35]:
while True:
    user_input = input("What is your problem? ")
    idx = get_menu_index(user_input)
    print("You should visit: ", menu[idx])

What is your problem? I have stomach pain
Distance: General Practitioner (GP) <> 1.2905598783130716 
Distance: Family Medicine Doctor <> 1.27568018609182 
Distance: Internal Medicine Doctor (Internist) <> 1.2534415307287636 
Distance: Cardiologist <> 1.2757344409551308 
Distance: Dermatologist <> 1.3072603790165216 
Distance: Endocrinologist <> 1.330028315687422 
Distance: Gastroenterologist <> 1.1772367941900543 
Distance: Hematologist <> 1.3336130332920981 
Distance: Nephrologist <> 1.3091630213215726 
Distance: Neurologist <> 1.288270211252427 
Distance: Oncologist <> 1.3085286191616177 
Distance: Pulmonologist <> 1.2924757218718879 
Distance: Rheumatologist <> 1.266092979884876 
Distance: General Surgeon <> 1.235516383457894 
Distance: Orthopedic Surgeon <> 1.3105408109858643 
Distance: Cardiothoracic Surgeon <> 1.2933666232358334 
Distance: Neurosurgeon <> 1.324890327670497 
Distance: Plastic Surgeon <> 1.2934158503132729 
Distance: Vascular Surgeon <> 1.3347511636351295 
Distance

KeyboardInterrupt: Interrupted by user

#How to get better performance:

1. Hunt for better model
2. Come up with a way of measure. Test cases
3. Also, if you are using a thresold, try to figure out best thresold.


In [36]:
# https://www.tensorflow.org/hub/tutorials/semantic_similarity_with_tf_hub_universal_encoder


In [ ]:
# What else can you build with this?

# Outliers and Anomaly detection

# Convert some of the text based characters of a user into numbers and the use these numbers as attributes of the user.

# Recommendation engine - Product to product

# Product Search - 

# 

In [37]:
# Note: If the list to search becomes very big move it to Vector Store such as milvus.

In [38]:
"One".lower() == "one"

True

In [41]:
model="text-embedding-3-small"
response = client.embeddings.create(
    model=model,
    input="How are you?"
)
response


CreateEmbeddingResponse(data=[Embedding(embedding=[0.027567066252231598, -0.026544300839304924, -0.027091361582279205, 0.057798076421022415, -0.0034756148234009743, -0.0028126018587499857, 0.03184840455651283, 0.010120609775185585, -0.0341080017387867, -0.04464485123753548, -0.03448856249451637, -0.009365429170429707, -0.02232242561876774, -0.0004307354101911187, -0.013248365372419357, 0.021335339173674583, -0.028542259708046913, 0.014699263498187065, 0.007979939691722393, 0.004073218442499638, 0.025735603645443916, -0.019123313948512077, 0.001523740473203361, 0.02275056019425392, 0.050567369908094406, -0.00046789980842731893, 0.006879874039441347, 0.046690378338098526, -0.010881736874580383, -0.023761430755257607, 0.04267067834734917, -0.03969752788543701, 0.025378825142979622, 0.03536861762404442, -0.007064209319651127, 0.0404110811650753, -0.057084519416093826, 0.020514748990535736, -0.004209983162581921, -0.06336382031440735, -0.002717460971325636, -0.04747529327869415, 0.010519011

In [47]:
response.data[0].embedding

[0.027567066252231598,
 -0.026544300839304924,
 -0.027091361582279205,
 0.057798076421022415,
 -0.0034756148234009743,
 -0.0028126018587499857,
 0.03184840455651283,
 0.010120609775185585,
 -0.0341080017387867,
 -0.04464485123753548,
 -0.03448856249451637,
 -0.009365429170429707,
 -0.02232242561876774,
 -0.0004307354101911187,
 -0.013248365372419357,
 0.021335339173674583,
 -0.028542259708046913,
 0.014699263498187065,
 0.007979939691722393,
 0.004073218442499638,
 0.025735603645443916,
 -0.019123313948512077,
 0.001523740473203361,
 0.02275056019425392,
 0.050567369908094406,
 -0.00046789980842731893,
 0.006879874039441347,
 0.046690378338098526,
 -0.010881736874580383,
 -0.023761430755257607,
 0.04267067834734917,
 -0.03969752788543701,
 0.025378825142979622,
 0.03536861762404442,
 -0.007064209319651127,
 0.0404110811650753,
 -0.057084519416093826,
 0.020514748990535736,
 -0.004209983162581921,
 -0.06336382031440735,
 -0.002717460971325636,
 -0.04747529327869415,
 0.01051901187747716

In [51]:
distances = [
("Rheumatologist", 1.3301625259276433 ), 
("General Surgeon", 1.384701890592811 ), 
("Orthopedic Surgeon", 1.3786663040297689 ), 
("Cardiothoracic Surgeon", 1.3853995322836703 ), 
("Neurosurgeon", 1.3597682378959948 ), 
("Plastic Surgeon", 1.3760686797364148 ), 
("Vascular Surgeon", 1.3941795204874583 ), 
("Pediatrician", 1.3419891764740626 ), 
("Pediatric Cardiologist", 1.3654635535946786 ), 
("Pediatric Neurologist", 1.3903308522880138 ), 
("Obstetrician (OB)", 1.3370184609282296 ), 
("Gynecologist (GYN)", 1.3318484206062482 ), 
("OB-GYN", 1.3260603448655297 ), 
("Psychiatrist", 1.3222153724618892 ), 
("Child Psychiatrist", 1.3632173175831672 ), 
("Psychologist", 1.3174748181078728 ), 
("Ophthalmologist", 1.35056467769898 ), 
("Optometrist", 1.3232069131098028 ), 
("Otolaryngologist (ENT)", 1.3753562405038524 ), 
("Allergist/Immunologist", 1.3795201238697172 ), 
("Anesthesiologist", 1.3727904561323965 ), 
("Radiologist", 1.360657116085388 ), 
("Pathologist", 1.3521313940263597 ), 
("Urologist", 1.2891085504210043 ), 
("Infectious Disease Specialist", 1.3251335450945234 ), 
]

distances1 = []
for doct, dist in distances:
    distances1.append((dist, doct))

In [52]:
distances1

[(1.3301625259276433, 'Rheumatologist'),
 (1.384701890592811, 'General Surgeon'),
 (1.3786663040297689, 'Orthopedic Surgeon'),
 (1.3853995322836703, 'Cardiothoracic Surgeon'),
 (1.3597682378959948, 'Neurosurgeon'),
 (1.3760686797364148, 'Plastic Surgeon'),
 (1.3941795204874583, 'Vascular Surgeon'),
 (1.3419891764740626, 'Pediatrician'),
 (1.3654635535946786, 'Pediatric Cardiologist'),
 (1.3903308522880138, 'Pediatric Neurologist'),
 (1.3370184609282296, 'Obstetrician (OB)'),
 (1.3318484206062482, 'Gynecologist (GYN)'),
 (1.3260603448655297, 'OB-GYN'),
 (1.3222153724618892, 'Psychiatrist'),
 (1.3632173175831672, 'Child Psychiatrist'),
 (1.3174748181078728, 'Psychologist'),
 (1.35056467769898, 'Ophthalmologist'),
 (1.3232069131098028, 'Optometrist'),
 (1.3753562405038524, 'Otolaryngologist (ENT)'),
 (1.3795201238697172, 'Allergist/Immunologist'),
 (1.3727904561323965, 'Anesthesiologist'),
 (1.360657116085388, 'Radiologist'),
 (1.3521313940263597, 'Pathologist'),
 (1.2891085504210043, 'Ur

In [53]:
distances1.sort()

In [57]:
for d, doc in distances1[:3]:
    print(f"{doc}")

Urologist
Psychologist
Psychiatrist


In [2]:
from absl import logging

import tensorflow as tf

import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re


module_url = "https://tfhub.dev/google/universal-sentence-encoder/4"
model = hub.load(module_url)
print ("module %s loaded" % module_url)
def embed(input):
  return model(input)

module https://tfhub.dev/google/universal-sentence-encoder/4 loaded


In [3]:
word = "Elephant"
sentence = "I am a sentence for which I would like to get its embedding."
paragraph = (
    "Universal Sentence Encoder embeddings also support short paragraphs. "
    "There is no hard limit on how long the paragraph is. Roughly, the longer "
    "the more 'diluted' the embedding will be.")
messages = [word, sentence, paragraph]

# Reduce logging output.
logging.set_verbosity(logging.ERROR)

message_embeddings = embed(messages)

for i, message_embedding in enumerate(np.array(message_embeddings).tolist()):
  print("Message: {}".format(messages[i]))
  print("Embedding size: {}".format(len(message_embedding)))
  message_embedding_snippet = ", ".join(
      (str(x) for x in message_embedding[:3]))
  print("Embedding: [{}, ...]\n".format(message_embedding_snippet))

Message: Elephant
Embedding size: 512
Embedding: [0.008344488218426704, 0.00048085825983434916, 0.06595248728990555, ...]

Message: I am a sentence for which I would like to get its embedding.
Embedding size: 512
Embedding: [0.050808604806661606, -0.0165242962539196, 0.01573782227933407, ...]

Message: Universal Sentence Encoder embeddings also support short paragraphs. There is no hard limit on how long the paragraph is. Roughly, the longer the more 'diluted' the embedding will be.
Embedding size: 512
Embedding: [-0.02833268791437149, -0.055862173438072205, -0.012941430322825909, ...]

